language: ruby
cache: bundler
addons:
  firefox: latest
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
before_install:
    - gem install bundler:1.17.2
script:
  - 'bundle exec rake rubocop'
  - 'bundle exec rails test'
  - 'bundle exec rails test:system'
